---
name: "Feature request"
description: "Proposez une idée pour ce projet"
body:
- type: markdown
  attributes:
    value: Avant de soumettre une nouvelle demande de fonctionnalité, consultez les demandes existantes pour voir si d'autres personnes ont déjà eu la même idée.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: J'ai rempli le modèle du mieux que j'ai pu.
        required: true
      - label: Ceci ne contient qu'une seule demande de fonctionnalité (si vous avez plusieurs demandes de fonctionnalités, ouvrez une demande de fonctionnalité pour chaque demande).
        required: true
      - label: Cette demande ne fait pas double des demandes de [fonctionnalités précédentes](https://github.com/hacf-fr/hass-ecoledirecte/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).
        required: true

- type: textarea
  attributes:
    label: "Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire."
    description: "Une description claire et concise du problème. Expliquer comment cela affecte vous et/ou votre configuration Home Assistant. Expliquer pourquoi cette fonctionnalité serait utile pour vous."
    placeholder: "Je suis toujours frustré quand [...]"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Décrivez la solution que vous souhaitez"
    description: "Une description claire et concise de ce que vous souhaitez obtenir."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Décrivez les alternatives que vous avez envisagées."
    description: "Une description claire et concise des solutions ou fonctionnalités alternatives que vous avez envisagées."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Contexte supplémentaire"
    description: "Ajoutez ici tout autre contexte ou captures d'écran concernant la demande de fonctionnalité."
  validations:
    required: true
