name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v7.0.1"

      - name: "Set up Node.js"
        uses: "actions/setup-node@v7.1.0"
        with:
          node-version: "20"
          cache: "npm"

      - name: "Install dependencies"
        shell: "bash"
        run: |
          npm ci

      - name: "Build cards"
        shell: "bash"
        run: |
          npm run build

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/ecole_directe/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/ecole_directe"
          zip ecole_directe.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v3.0.3
        with:
          files: ${{ github.workspace }}/custom_components/ecole_directe/ecole_directe.zip
